/**
 * Source-backed KJSEA paper metadata.
 *
 * This module stores format metadata, mark allocations, durations, and
 * prompt-safe conventions. It does not reproduce sample-paper question text.
 */
import type { Difficulty, ExamBlueprint, ExamBlueprintSection, PaperVariant, QuestionType } from './exam-schema.js';

const normalizeKey = (value: unknown): string => String(value ?? '').toLowerCase().replace(/[^a-z0-9]+/g, '');
export type KJSEASubjectKey = 'english' | 'kiswahili' | 'mathematics' | 'integratedscience' | 'agriculture' | 'pretechnical' | 'socialstudies' | 'cre' | 'ire' | 'creativearts';
export type KJSEACardVariant = PaperVariant | 'both';
export interface KJSEAComponent { label: string; marks: number; detail: string; }
export interface KJSEAPaperSpec { subjectKey: KJSEASubjectKey; variant: 'paper1' | 'paper2' | 'single'; title: string; code: string; marks: number; duration_minutes: number; components: KJSEAComponent[]; format_notes: string[]; sources: string[]; }

const KNEC_TIMETABLE = 'https://www.knec.ac.ke/wp-content/uploads/2026/02/2026-KJSEA-TIMETABLE.pdf';
const KNEC_REGULATIONS = 'https://www.knec.ac.ke/wp-content/uploads/2026/02/KJSEA-REGULATIONS.pdf';
const KNEC_SAMPLE_CIRCULAR = 'https://www.knec.ac.ke/wp-content/uploads/2025/06/CIRCULAR-ON-ACCESSING-KJSEA-SAMPLE-PAPER-8.pdf';
const SOURCES = [KNEC_TIMETABLE, KNEC_REGULATIONS, KNEC_SAMPLE_CIRCULAR];
const SAMPLE_SOURCE_URLS: Record<string, string[]> = {
  'english-paper1': ['https://drive.google.com/uc?export=download&id=18A4kOYH2pMdpCLwxbJEbbbCWjfE3fAlG', 'https://arena.co.ke/knec-grade-9-kjsea-examinable-papers-and-test-areas/', 'https://www.examwise.co.ke/'],
  'english-paper2': ['https://drive.google.com/uc?export=download&id=1BPagBkrGv7wysZFHsCpNx7ORkqFG088o', 'https://arena.co.ke/knec-official-grade-9-kjsea-assessment-papers-theory-and-practicals/', 'https://www.examwise.co.ke/'],
  'kiswahili-paper1': ['https://drive.google.com/uc?export=download&id=1_iELtrolxxt_86USJGxyNhsEUMR0Pipu', 'https://arena.co.ke/knec-official-grade-9-kjsea-assessment-papers-theory-and-practicals/', 'https://www.examwise.co.ke/'],
  'kiswahili-paper2': ['https://drive.google.com/uc?export=download&id=12gw3jPEtKYsIZhu85tzmwWiowqFmqP6T', 'https://www.notes.co.ke/notes/6326/kjsea-kiswahili-insha-na-utangulizi-wa-fasihi-sample-paper', 'https://www.examwise.co.ke/'],
  'integratedscience-paper1': ['https://drive.google.com/uc?export=download&id=1K3VzbT1Q4McYs5CfALO6E0ZcUGNakewh', 'https://arena.co.ke/knec-official-grade-9-kjsea-assessment-papers-theory-and-practicals/', 'https://www.examwise.co.ke/'],
  'integratedscience-paper2': ['https://drive.google.com/uc?export=download&id=1Yfe31QLKUj4jTQ5puUfg05H-iMgx76pf', 'https://www.easyelimu.com/exams/14-junior-secondary/34-grade-9-exams/41-2025-grade-9-exams/67-cbc-grade-9-exams-term-1-2025/361-set-3-grade-9-openers-exams-term-1-2025/3393-kjsea-grade-9-integrated-science-p2-openers-exams-term-1-2025-set-3', 'https://www.examwise.co.ke/app/question-predictor?grade=9&subject=integrated-science-paper2'],
};
const SAMPLE_STYLE_GUIDANCE: Record<string, string> = {
  'english-paper1': 'Use the continuous Q1–50 objective flow: reading comprehension, listening and speaking, cloze, then grammar and language use. Use prose stimuli and A–D options; do not add open sub-parts.',
  'english-paper2': 'Use a formal two-section constructed-response paper with Q1 composition, then Q2 oral literature, Q3 poetry, Q4 play and Q5 novella. Use literary extracts, speaker labels and stage directions where relevant; use parenthetical mark notation and lettered sub-parts.',
  'kiswahili-paper1': 'Use the continuous Q1–50 one-best-answer flow: ufahamu wa kusoma, kusikiliza na kuzungumza, cloze and sarufi. Include a data-table stimulus only when the selected item calls for it.',
  'kiswahili-paper2': 'Use two sections: Insha Q1 (300–350 words) and Fasihi Q2–Q5 covering Fasihi Simulizi, Novela, Tamthilia and Ushairi. Construct explicit (a)–(f) sub-parts with Kiswahili alama notation and exact parent-mark totals.',
  'integratedscience-paper1': 'Use Section A Q1–30 as A–D objective items and Section B Q31–40 as written structured tasks. Use embedded tables, hazard symbols, circuits, organs, magnets and other readable diagrams only when they support the selected science context; keep shared stimuli tied to adjacent questions.',
  'integratedscience-paper2': 'Use the current written practical-skills format with three compulsory science tasks spanning Chemistry, Biology and Physics. Use apparatus, observations, measurements, safety and conclusions; follow the current official sample/rubric for the exact mark split.',
};
const SUBJECT_ALIASES: Record<KJSEASubjectKey, string[]> = {
  english: ['english'], kiswahili: ['kiswahili'], mathematics: ['mathematics', 'maths', 'math'],
  integratedscience: ['integrated science', 'integratedscience', 'science'], agriculture: ['agriculture', 'agriculture and nutrition'],
  pretechnical: ['pre-technical studies', 'pre technical studies', 'pretechnical'], socialstudies: ['social studies', 'socialstudies'],
  cre: ['cre', 'christian religious education'], ire: ['ire', 'islamic religious education'], creativearts: ['creative arts', 'creative arts and sports', 'creativearts'],
};
export function kjseaSubjectKey(subject: unknown): KJSEASubjectKey | null {
  const key = normalizeKey(subject);
  const candidates = Object.keys(SUBJECT_ALIASES) as KJSEASubjectKey[];
  return candidates.find((candidate) => SUBJECT_ALIASES[candidate].some((alias) => normalizeKey(alias) === key))
    || candidates.find((candidate) => SUBJECT_ALIASES[candidate].some((alias) => normalizeKey(alias).length >= 5 && key.includes(normalizeKey(alias))))
    || null;
}
export const TWO_PAPER_SUBJECTS: KJSEASubjectKey[] = ['english', 'kiswahili', 'integratedscience', 'agriculture', 'pretechnical', 'creativearts'];
export function subjectHasTwoPapers(subject: unknown): boolean { const key = kjseaSubjectKey(subject); return Boolean(key && TWO_PAPER_SUBJECTS.includes(key)); }
const notes = (extra: string[] = []) => [...extra, 'Use original questions and answers; do not reproduce any source-paper wording.'];
const makeSpec = (subjectKey: KJSEASubjectKey, variant: 'paper1' | 'paper2' | 'single', title: string, code: string, marks: number, duration_minutes: number, components: KJSEAComponent[], extra: string[] = []): KJSEAPaperSpec => ({ subjectKey, variant, title, code, marks, duration_minutes, components, format_notes: notes(extra), sources: [...SOURCES, ...(SAMPLE_SOURCE_URLS[`${subjectKey}-${variant}`] || [])] });

const PAPER_DATA: Record<KJSEASubjectKey, { paper1: KJSEAPaperSpec; paper2: KJSEAPaperSpec }> = {
  english: { paper1: makeSpec('english', 'paper1', 'Paper 1 · English (Reading Comprehension, Oral Skills and Grammar)', '901/1', 50, 100, [{ label: 'Reading comprehension · Q1–20', marks: 20, detail: 'Four prose passage groups: Q1–6, Q7–11, Q12–16, Q17–20' }, { label: 'Listening and speaking · Q21–25', marks: 5, detail: 'Dialogue completion and situational responses' }, { label: 'Cloze test · Q26–35', marks: 10, detail: 'Ten blanks in one passage' }, { label: 'Grammar and language use · Q36–50', marks: 15, detail: 'Completion, punctuation, transformation, combination, meaning and idiom' }], ['Fifty continuous compulsory multiple-choice questions, numbered 1–50, with options A–D. No open-response sub-parts or printed item-level mark brackets. The sample header is KJSEA 901/1, January 2025, 1 hour 40 minutes.']), paper2: makeSpec('english', 'paper2', 'Paper 2 · English (Composition and Literary Analysis)', '901/2', 50, 105, [{ label: 'Section A · Composition · Q1', marks: 15, detail: 'One imaginative composition with ruled response space' }, { label: 'Section B · Oral literature · Q2', marks: 10, detail: 'Narrative-based identification, character, style and moral-lesson tasks' }, { label: 'Section B · Poetry · Q3', marks: 5, detail: 'Line count, rhyme and interpretation' }, { label: 'Section B · Play · Q4', marks: 10, detail: 'Extract-based setting, issue, character and social-practice analysis' }, { label: 'Section B · Novella · Q5', marks: 10, detail: 'Extract-based setting, character and dialogue analysis' }], ['Five compulsory tasks numbered 1–5. Sub-parts use (a), (b), (c) and nested Roman items. Marks use parenthetical notation such as (15 MARKS).']) },
  kiswahili: { paper1: makeSpec('kiswahili', 'paper1', 'Karatasi ya Kwanza · Kiswahili Lugha', '902/1', 50, 100, [{ label: 'Ufahamu wa kusoma · Q1–20', marks: 20, detail: 'Four reading passages, including a data-table reading task at Q18–20' }, { label: 'Kusikiliza na kuzungumza · Q21–25', marks: 5, detail: 'Scripted dialogue/task block' }, { label: 'Cloze · Q26–35', marks: 10, detail: 'Passage with numbered blanks and four options' }, { label: 'Sarufi na matumizi ya lugha · Q36–50', marks: 15, detail: 'Standalone language-use multiple-choice items' }], ['Fifty sequential one-best-answer multiple-choice questions, Q1–Q50, with A–D options. The January booklet uses task directions rather than formal Section A/B labels; the sample header is 902/1, January 2025, Saa 1 dakika 40.']), paper2: makeSpec('kiswahili', 'paper2', 'Karatasi ya Pili · Kiswahili (Insha na Utangulizi wa Fasihi)', '902/2', 50, 105, [{ label: 'Sehemu A · Insha · Q1', marks: 15, detail: 'One functional-writing task, recommended 300–350 words' }, { label: 'Sehemu B · Fasihi Simulizi · Q2', marks: 10, detail: 'Six sub-parts totalling 2+2+1+2+2+1' }, { label: 'Sehemu B · Novela · Q3', marks: 10, detail: 'Five sub-parts at 2 marks each' }, { label: 'Sehemu B · Tamthilia · Q4', marks: 10, detail: 'Four sub-parts totalling 2+4+2+2' }, { label: 'Sehemu B · Ushairi · Q5', marks: 5, detail: 'Three sub-parts totalling 2+1+2' }], ['Five compulsory constructed-response questions. Marks use Kiswahili parenthetical notation such as (alama 2), and the sample header is 902/2, January 2025, Saa 1 dakika 45.']) },
  mathematics: { paper1: makeSpec('mathematics', 'single', 'Mathematics', '903', 100, 120, [{ label: 'Section A · Multiple choice', marks: 20, detail: 'Twenty MCQs' }, { label: 'Section B · Structured and essay questions', marks: 80, detail: 'Structured and essay questions; exact question count and strand allocation must follow the current official sample/rubric' }], ['One paper only. Section A has 20 MCQs worth 20 marks; Section B carries 80 marks. Do not invent a strand-level marks split or expose Paper 2.']), paper2: makeSpec('mathematics', 'paper2', 'Not applicable', '903', 0, 0, []) },
  integratedscience: { paper1: makeSpec('integratedscience', 'paper1', 'Paper 1 · Integrated Science (Theory)', '905/1', 70, 100, [{ label: 'Section A · Multiple choice · Q1–30', marks: 30, detail: 'Four-option objective questions across biology, chemistry and physics, with diagrams and tables' }, { label: 'Section B · Structured and essay questions', marks: 40, detail: 'Written structured/essay science tasks; exact internal allocation follows the current official sample/rubric' }], ['Section A uses a separate answer sheet; Section B is answered in the paper.']), paper2: makeSpec('integratedscience', 'paper2', 'Paper 2 · Integrated Science (Written practical skills)', '905/2', 30, 60, [{ label: 'Written practical skills · three questions', marks: 30, detail: 'Current regulations describe three questions assessing practical skills across Chemistry, Biology and Physics; follow the live official sample/rubric for the exact split' }], ['Current KNEC regulations and the 2026 timetable set Paper 2 at 60 minutes. Older 2025 sample papers show a two-task, 90-minute version; preserve that as historical evidence only, not the current default.']) },
  agriculture: { paper1: makeSpec('agriculture', 'paper1', 'Paper 1 · Agriculture Theory', '906/1', 70, 100, [{ label: 'Section A · Multiple choice', marks: 30, detail: 'Thirty MCQs' }, { label: 'Section B · Structured and essay questions', marks: 40, detail: 'Structured and essay questions' }]), paper2: makeSpec('agriculture', 'paper2', 'Paper 2 · Agriculture Practical Project', '906/2', 30, 0, [{ label: 'Practical/project assessment', marks: 30, detail: 'Practical/project work completed within the KJSEA project window' }], ['The current timetable states the project as a period rather than a timed duration; do not render 150 minutes.']) },
  pretechnical: { paper1: makeSpec('pretechnical', 'paper1', 'Paper 1 · Pre-Technical Studies', '912/1', 80, 100, [{ label: 'Section A · Multiple choice', marks: 30, detail: 'Thirty MCQs' }, { label: 'Section B · Structured and essay questions', marks: 50, detail: 'Structured and essay questions' }]), paper2: makeSpec('pretechnical', 'paper2', 'Paper 2 · Pre-Technical Project', '912/2', 40, 0, [{ label: 'Project', marks: 40, detail: 'One-month project window' }], ['Project duration is one month; represented as a project window, not minutes.']) },
  creativearts: { paper1: makeSpec('creativearts', 'paper1', 'Paper 1 · Creative Arts & Sports Integrated Project', '911/1', 100, 0, [{ label: 'Integrated project', marks: 100, detail: 'Performing Arts, Visual Arts and Sports project completed over three months' }], ['Project duration is three months; represented as a project window, not minutes.']), paper2: makeSpec('creativearts', 'paper2', 'Paper 2 · Creative Arts & Sports', '911/2', 100, 100, [{ label: 'Section A · Multiple choice', marks: 40, detail: 'Forty MCQs' }, { label: 'Section B · Structured', marks: 60, detail: 'Structured questions' }]) },
  socialstudies: { paper1: makeSpec('socialstudies', 'single', 'Social Studies', '907', 100, 90, [{ label: 'Section A · Multiple choice', marks: 20, detail: 'Twenty MCQs' }, { label: 'Section B · Structured', marks: 80, detail: 'Structured questions; questions 21–23 require actual maps' }], ['Questions 21–23 must contain a Kenya, Africa, or topographical map visual where mapwork is requested.']), paper2: makeSpec('socialstudies', 'paper2', 'Not applicable', '907/2', 0, 0, []) },
  cre: { paper1: makeSpec('cre', 'single', 'Christian Religious Education', '908', 100, 90, [{ label: 'Section A · Multiple choice', marks: 20, detail: 'Twenty MCQs' }, { label: 'Section B · Structured', marks: 80, detail: 'Structured questions' }]), paper2: makeSpec('cre', 'paper2', 'Not applicable', '908/2', 0, 0, []) },
  ire: { paper1: makeSpec('ire', 'single', 'Islamic Religious Education', '909', 100, 90, [{ label: 'Section A · Multiple choice', marks: 20, detail: 'Twenty MCQs' }, { label: 'Section B · Structured', marks: 80, detail: 'Structured questions' }]), paper2: makeSpec('ire', 'paper2', 'Not applicable', '909/2', 0, 0, []) },
};

function section(id: string, title: string, question_type: QuestionType, count: number, marks_per_question: number, difficulty: Difficulty): ExamBlueprintSection { return { id, title, question_type, count, marks_per_question, difficulty }; }
function paperSections(subjectKey: KJSEASubjectKey, variant: 'paper1' | 'paper2', difficulty: Difficulty): ExamBlueprintSection[] {
  if (subjectKey === 'mathematics') return variant === 'paper2' ? [] : [section('kjsea-mathematics-mcq', 'Section A: Multiple Choice Questions', 'multiple_choice', 20, 1, difficulty), section('kjsea-mathematics-section-b', 'Section B: Structured and essay questions', 'short_answer', 16, 5, difficulty)];
  if (subjectKey === 'socialstudies' || subjectKey === 'cre' || subjectKey === 'ire') return variant === 'paper2' ? [] : [section(`kjsea-${subjectKey}-mcq`, 'Section A: Multiple Choice Questions', 'multiple_choice', 20, 1, difficulty), section(`kjsea-${subjectKey}-structured`, 'Section B: Structured questions', 'case_study', 16, 5, difficulty)];
  if (subjectKey === 'integratedscience' && variant === 'paper1') return [section('kjsea-is-p1-mcq', 'Section A: Multiple Choice Questions · Q1–30', 'multiple_choice', 30, 1, difficulty), section('kjsea-is-p1-task1', 'Section B: Task 1 · Q31', 'case_study', 1, 3, difficulty), section('kjsea-is-p1-task2a', 'Section B: Task 2 · Q32', 'case_study', 1, 4, difficulty), section('kjsea-is-p1-task2b', 'Section B: Task 2 · Q33', 'case_study', 1, 4, difficulty), section('kjsea-is-p1-task2c', 'Section B: Task 2 · Q34', 'case_study', 1, 5, difficulty), section('kjsea-is-p1-task3', 'Section B: Task 3 · Q35–38', 'case_study', 4, 4, difficulty), section('kjsea-is-p1-task4', 'Section B: Task 4 · Q39–40', 'case_study', 2, 4, difficulty)];
  if (subjectKey === 'integratedscience' && variant === 'paper2') return [section('kjsea-is-p2-q1', 'Question 1 · Chemistry practical skills', 'case_study', 1, 10, difficulty), section('kjsea-is-p2-q2', 'Question 2 · Biology practical skills', 'case_study', 1, 10, difficulty), section('kjsea-is-p2-q3', 'Question 3 · Physics practical skills', 'case_study', 1, 10, difficulty)];
  if ((subjectKey === 'agriculture' || subjectKey === 'pretechnical') && variant === 'paper1') return [section(`kjsea-${subjectKey}-p1-mcq`, 'Section A: Multiple Choice Questions', 'multiple_choice', 30, 1, difficulty), section(`kjsea-${subjectKey}-p1-structured`, 'Section B: Structured', 'case_study', subjectKey === 'agriculture' ? 8 : 10, 5, difficulty)];
  if (subjectKey === 'agriculture' && variant === 'paper2') return [section('kjsea-agriculture-p2-practical', 'Practical paper', 'case_study', 3, 10, difficulty)];
  if (subjectKey === 'pretechnical' && variant === 'paper2') return [section('kjsea-pretechnical-p2-project', 'Project', 'case_study', 1, 40, difficulty)];
  if (subjectKey === 'creativearts' && variant === 'paper1') return [section('kjsea-creativearts-p1-project', 'Project', 'case_study', 1, 100, difficulty)];
  if (subjectKey === 'creativearts' && variant === 'paper2') return [section('kjsea-creativearts-p2-mcq', 'Section A: Multiple Choice Questions', 'multiple_choice', 40, 1, difficulty), section('kjsea-creativearts-p2-structured', 'Section B: Structured', 'case_study', 12, 5, difficulty)];
  if (variant === 'paper1') return [section(`kjsea-${subjectKey}-p1-comprehension`, 'Reading comprehension · Questions 1–20', 'multiple_choice', 20, 1, difficulty), section(`kjsea-${subjectKey}-p1-oral`, 'Listening and speaking · Questions 21–25', 'multiple_choice', 5, 1, difficulty), section(`kjsea-${subjectKey}-p1-cloze`, 'Cloze test · Questions 26–35', 'multiple_choice', 10, 1, difficulty), section(`kjsea-${subjectKey}-p1-grammar`, 'Grammar and language use · Questions 36–50', 'multiple_choice', 15, 1, difficulty)];
  return subjectKey === 'kiswahili'
    ? [section('kjsea-kiswahili-p2-insha', 'Sehemu A: Insha · Swali la 1', 'essay', 1, 15, difficulty), section('kjsea-kiswahili-p2-fasihi-simulizi', 'Sehemu B: Fasihi Simulizi · Swali la 2', 'case_study', 1, 10, difficulty), section('kjsea-kiswahili-p2-novela', 'Sehemu B: Novela · Swali la 3', 'case_study', 1, 10, difficulty), section('kjsea-kiswahili-p2-tamthilia', 'Sehemu B: Tamthilia · Swali la 4', 'case_study', 1, 10, difficulty), section('kjsea-kiswahili-p2-ushairi', 'Sehemu B: Ushairi · Swali la 5', 'case_study', 1, 5, difficulty)]
    : [section('kjsea-english-p2-composition', 'Section A: Composition · Question 1', 'essay', 1, 15, difficulty), section('kjsea-english-p2-oral', 'Section B: Oral literature · Question 2', 'case_study', 1, 10, difficulty), section('kjsea-english-p2-poetry', 'Section B: Poetry · Question 3', 'case_study', 1, 5, difficulty), section('kjsea-english-p2-play', 'Section B: Play · Question 4', 'case_study', 1, 10, difficulty), section('kjsea-english-p2-novella', 'Section B: Novella · Question 5', 'case_study', 1, 10, difficulty)];
}
export function getKjseaPaperSpec(subject: unknown, variant: KJSEACardVariant = 'single'): KJSEAPaperSpec | null {
  const subjectKey = kjseaSubjectKey(subject); if (!subjectKey) return null;
  if (!subjectHasTwoPapers(subjectKey)) return variant === 'single' ? { ...PAPER_DATA[subjectKey].paper1, variant: 'single' } : null;
  if (variant === 'paper1' || variant === 'paper2') return PAPER_DATA[subjectKey][variant];
  const p1 = PAPER_DATA[subjectKey].paper1; const p2 = PAPER_DATA[subjectKey].paper2;
  return { subjectKey, variant: 'single', title: 'Whole subject · Paper 1 + Paper 2', code: `${p1.code} + ${p2.code}`, marks: p1.marks + p2.marks, duration_minutes: p1.duration_minutes + p2.duration_minutes, components: [{ label: p1.title, marks: p1.marks, detail: `${p1.duration_minutes} minutes` }, { label: p2.title, marks: p2.marks, detail: `${p2.duration_minutes} minutes` }], format_notes: [...p1.format_notes, ...p2.format_notes], sources: SOURCES };
}
export function makeKjseaBlueprint(subject: unknown, variant: PaperVariant = 'single', difficulty: Difficulty = 'mixed'): ExamBlueprint | undefined {
  const subjectKey = kjseaSubjectKey(subject); if (!subjectKey) return undefined;
  const sections = variant === 'single' && subjectHasTwoPapers(subjectKey) ? [...paperSections(subjectKey, 'paper1', difficulty), ...paperSections(subjectKey, 'paper2', difficulty)] : paperSections(subjectKey, variant === 'single' ? 'paper1' : variant, difficulty);
  return { sections, total_marks: sections.reduce((sum, item) => sum + item.count * item.marks_per_question, 0), estimated_minutes: getKjseaPaperSpec(subject, variant)?.duration_minutes, paper_variant: variant };
}
export function kjseaFormatInstruction(subject: unknown, variant: PaperVariant = 'single'): string {
  const resolved = getKjseaPaperSpec(subject, variant); if (!resolved) return '';
  const componentText = resolved.components.map((component) => `${component.label} (${component.marks} marks): ${component.detail}`).join('; ');
  const skeleton = variant === 'paper1' ? 'Paper 1 skeleton: candidate instructions -> Section A/objective items -> option labels A-D -> answer-sheet reminder.' : variant === 'paper2' ? 'Paper 2 skeleton: candidate instructions -> project/practical/structured tasks -> lettered sub-parts with marks -> marking-scheme headings.' : 'Whole-paper skeleton: formal header -> labelled sections -> numbered questions -> lettered sub-parts -> separate marking scheme.';
  const sampleGuidance = SAMPLE_STYLE_GUIDANCE[`${kjseaSubjectKey(subject)}-${variant}`] || '';
  return [`KJSEA paper format: ${resolved.title}, ${resolved.marks} marks, ${resolved.duration_minutes} minutes.`, `Required components: ${componentText}.`, 'Format-only skeleton (not source content): header, candidate instructions, labelled sections, numbered questions, lettered sub-parts, printed marks, and marking-scheme headings.', sampleGuidance, ...resolved.format_notes, 'Header must include school, grade, subject, paper code, date, duration and total marks.', skeleton, 'Generate original questions; do not reproduce any source paper question, answer, or marking-scheme text.'].join(' ');
}
export const KJSEA_FORMAT_SOURCES = SOURCES;
