import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { getSchoolLevelBand, calculateGradeForClass, gradeLabelForClass, gradePointsMaxForClass, generateSubjectSpecificComment, is844Curriculum } from './grading';
import type { SchoolLevelBand, SubjectResult } from './grading';
import { pdfFontSize } from './pdfFontSize';
import QRCode from 'qrcode';
import { calculatePathwayPerformance, formatPathwayNumber, strongestPathway } from './pathwayPerformance';
import { isExcludedResult, usesSevenSubjectRanking } from './learnerTotals';

// ── Shared PDF Helper Functions for Report Cards ─────────────────────────────

export interface SchoolInfo {
  name: string;
  motto?: string;
  logo_url?: string | null;
  principal_name?: string;
  address?: string;
  phone?: string;
  email?: string;
  next_term_start_date?: string | null;
  school_closes_on?: string | null;
  school_opens_on?: string | null;
  report_class?: string;
  report_term?: string;
  report_assessment?: string;
  report_year?: string | number;
}

export interface SignatureInfo {
  principal_signature_url?: string | null;
  teacher_signature_url?: string | null;
}

export interface ReportCardQrOptions {
  assessmentNumber?: string | null;
  loginUrl?: string;
}

export interface ReportCardLearnerIdentity {
  name: string;
  photoUrl?: string | null;
}

export interface StudentResult {
  subjects?: { name?: string } | null;
  marks?: number;
  out_of?: number;
  percentage?: number | null;
  [key: string]: any;
}

export interface ReportCardSubjectRow {
  subjects?: { name?: string } | null;
  marks?: number;
  out_of?: number;
  percentage?: number | null;
  previousPercentage?: number | null;
  streamPosition?: number | null;
  streamTotal?: number | null;
  classPosition?: number | null;
  classTotal?: number | null;
  teacherComment?: string | null;
  teacherName?: string | null;
  assessmentValues?: Record<string, { marks: number; outOf: number; percentage: number } | number | null>;
}

export interface ReportCardTableOptions {
  showStreamPosition?: boolean;
  showDeviation?: boolean;
  previousAssessmentLabel?: string;
  assessmentColumns?: { id: string; label: string }[];
  rankingDetails?: { subjects: string[]; totalMarks: number; totalPoints: number };
}

const REPORT_CONTENT_TOP = 5;
const REPORT_CONTENT_BOTTOM_MARGIN = 8;
/**
 * The footer is drawn at pageHeight - 6.  Keep the signature/QR/calendar
 * block above that footer instead of letting a late helper move it to another
 * page or paint it over the comment.
 */
export const REPORT_CARD_FOOTER_GAP = 8;
export const REPORT_CARD_COMMENT_GAP = 2;
/**
 * Comments are normally generated by the fixed templates above and fit at
 * the normal compact size.  For arbitrary supplied text we fit down to this
 * floor and cap the rendered wrapped block at this many lines.  This is an
 * explicit bounded policy: it prevents overlap/extra pages when an
 * unbounded comment cannot physically fit on A4.  No truncation occurs while
 * the text fits in the reserved box.
 */
export const REPORT_CARD_COMMENT_MIN_FONT_SIZE = 4.5;
export const REPORT_CARD_COMMENT_MAX_LINES = 16;

export interface ReportCardSignatureLayout {
  hasQr: boolean;
  coreHeight: number;
  calendarNoticeLines: string[];
  totalHeight: number;
}

function reportCardCalendarNoticeLines(schoolInfo?: SchoolInfo): string[] {
  const closingDate = schoolInfo?.school_closes_on
    ? new Date(`${schoolInfo.school_closes_on}T00:00:00`).toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })
    : '';
  const openingDate = schoolInfo?.school_opens_on
    ? new Date(`${schoolInfo.school_opens_on}T00:00:00`).toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })
    : schoolInfo?.next_term_start_date
      ? new Date(`${schoolInfo.next_term_start_date}T00:00:00`).toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })
      : '';
  return [
    closingDate ? `School closes on: ${closingDate}` : '',
    openingDate ? `School opens on: ${openingDate}` : '',
  ].filter(Boolean);
}

export function getReportCardSignatureLayout(
  schoolInfo?: SchoolInfo,
  qrOptions: ReportCardQrOptions = {},
): ReportCardSignatureLayout {
  const hasQr = Boolean(qrOptions.loginUrl || qrOptions.assessmentNumber || typeof window !== 'undefined');
  const coreHeight = COMPACT_MODE ? (hasQr ? 38 : 14) : (hasQr ? 52 : 34);
  const calendarNoticeLines = reportCardCalendarNoticeLines(schoolInfo);
  return {
    hasQr,
    coreHeight,
    calendarNoticeLines,
    totalHeight: coreHeight + (calendarNoticeLines.length > 0 ? (COMPACT_MODE ? 12 : 15) : 5),
  };
}

/** Top of the fixed bottom signature/QR/calendar zone. */
export function getReportCardSignatureZoneTop(
  doc: jsPDF,
  schoolInfo?: SchoolInfo,
  qrOptions: ReportCardQrOptions = {},
): number {
  return doc.internal.pageSize.getHeight() - REPORT_CARD_FOOTER_GAP - getReportCardSignatureLayout(schoolInfo, qrOptions).totalHeight;
}

/** Bottom edge available to the required class-teacher comment box. */
export function getReportCardCommentBottomY(
  doc: jsPDF,
  schoolInfo?: SchoolInfo,
  qrOptions: ReportCardQrOptions = {},
): number {
  return getReportCardSignatureZoneTop(doc, schoolInfo, qrOptions) - REPORT_CARD_COMMENT_GAP;
}

/**
 * COMPACT (ONE-PAGE) MODE
 * Reduces fonts, paddings and vertical spacing so a full report card
 * (header + student info + 13-subject table + summary + trend + comment +
 * signatures) fits on a single A4 page.
 */
// Readable multi-section layout: allow safe pagination instead of squeezing text into overlapping rows.
export const COMPACT_MODE = true;
const ROW = COMPACT_MODE ? 3.2 : 5;   // vertical row step for student info (further reduced)
const HDR_H = COMPACT_MODE ? 30 : 42; // reference-style white identity header

export const REPORT_CARD_CORNER_SIZE = 22;
export const REPORT_CARD_CORNER_Y = 3;
export const REPORT_CARD_LOGO_X = (210 - REPORT_CARD_CORNER_SIZE) / 2;
export const REPORT_CARD_PHOTO_X = 174;

/**
 * Starts a clean continuation page when a report-card block cannot fit in the
 * remaining printable space. The returned Y coordinate is always safe to draw.
 */
export function ensureReportCardSpace(doc: jsPDF, y: number, requiredHeight: number): number {
  const pageHeight = doc.internal.pageSize.getHeight();
  if (y + requiredHeight <= pageHeight - REPORT_CONTENT_BOTTOM_MARGIN) return y;
  // A report card is a single A4 page. Never move the cursor backwards (that
  // would paint a later block over an earlier one) and never create a hidden
  // continuation page here. Callers must omit optional sections when this
  // guard says the remaining page budget is insufficient.
  return y;
}

export const SUBJECT_ORDER = [
  'English',
  'Kiswahili',
  'Mathematics',
  'Integrated Science',
  'Pre-Technical Studies',
  'Agriculture',
  'Social Studies',
  'CRE',
  'Creative Arts',
  'Science and Technology',
  'Physical and Health Education',
  'IRE',
  'HRE'
];

export function sortResultsBySubject(results: any[]) {
  return [...results].sort((a, b) => {
    const nameA = a.subjects?.name || '';
    const nameB = b.subjects?.name || '';
    const indexA = SUBJECT_ORDER.findIndex(s => nameA.toLowerCase().includes(s.toLowerCase()));
    const indexB = SUBJECT_ORDER.findIndex(s => nameB.toLowerCase().includes(s.toLowerCase()));
    if (indexA === -1 && indexB === -1) return nameA.localeCompare(nameB);
    if (indexA === -1) return 1;
    if (indexB === -1) return -1;
    return indexA - indexB;
  });
}

export function getPercentage(result: any): number {
  if (result.percentage !== undefined && result.percentage !== null) return Number(result.percentage);
  const outOf = Number(result.out_of || 100);
  return outOf > 0 ? Math.round((Number(result.marks || 0) / outOf) * 100) : 0;
}

export function gradeFromPercentage(percentage: number, classData: any) {
  const g = calculateGradeForClass(percentage, classData);
  return { grade: gradeLabelForClass(percentage, classData), points: g.points || null, descriptor: g.descriptor };
}

export function overallGradeLabel(avgPct: number, classData?: any) {
  return gradeFromPercentage(avgPct, classData).grade;
}

export function ordinal(n: number): string {
  const v = n % 100;
  if (v >= 11 && v <= 13) return `${n}th`;
  switch (n % 10) {
    case 1: return `${n}st`;
    case 2: return `${n}nd`;
    case 3: return `${n}rd`;
    default: return `${n}th`;
  }
}

export function formatPosition(position: number | null, totalStudents: number): string {
  if (!position) return 'N/A';
  return `${ordinal(position)} out of ${totalStudents || '—'}`;
}

// ── Legacy AI Comment Generator (kept for backward compatibility) ─────────────
const COMMENT_TEMPLATES = {
  top1: [
    "Exceptional performance! You ranked 1st out of {total} learners. Your mastery of {bestSubject} is remarkable, and your dedication sets a brilliant example. With your {grade} grade ({descriptor}), you demonstrate that excellence is a habit. Continue being the trailblazer you are!",
    "Magnificent work! Securing 1st position among {total} learners requires extraordinary commitment. Your {grade} grade in {bestSubject} reflects exceptional understanding. You are an inspiration to your peers — keep shining brilliantly!",
  ],
  top2: [
    "Outstanding achievement! You claimed 2nd place among {total} learners. Your proficiency in {bestSubject} is impressive, earning a {grade} grade ({descriptor}). A little more effort and the top spot is yours!",
    "Brilliant performance! 2nd position out of {total} learners showcases your determination. Your strength in {bestSubject} with a {grade} grade is praiseworthy. Keep pushing boundaries!",
  ],
  top3: [
    "Excellent effort! You earned 3rd place out of {total} learners. Your dedication to {bestSubject} has paid off with a {grade} grade ({descriptor}). Consistency will take you even higher!",
    "Wonderful work! Ranking 3rd among {total} learners demonstrates serious commitment. Your {grade} grade in {bestSubject} proves you have what it takes. Aim for the stars!",
  ],
  top5: [
    "Great work! You are among the top 5 performers in a class of {total}. Your {grade} grade in {bestSubject} shows tremendous potential. With continued focus, especially on {weakestSubject}, you will reach even greater heights!",
    "Commendable performance! Being in the top 5 out of {total} learners reflects your hard work. Your {grade} grade in {bestSubject} is excellent. Keep building on this strong foundation!",
  ],
  newStudent: [
    "Welcome! You have achieved a {grade} grade overall ({descriptor}). Your performance in {bestSubject} shows great promise. Focus on strengthening {weakestSubject} next term. We believe in your incredible potential!",
    "A warm welcome! Your {grade} grade ({descriptor}) indicates a solid start. You show particular aptitude in {bestSubject}. Devoting more time to {weakestSubject} will help you flourish. Exciting times ahead!",
  ],
  improved10: [
    "Remarkable improvement! You rose by {dev}% from last term — a phenomenal leap! Your relentless effort in {bestSubject} has truly paid off with a {grade} grade ({descriptor}). This momentum will carry you to extraordinary achievements!",
    "Phenomenal progress! A {dev}% increase from last term is truly inspiring. Your determination in {bestSubject} earned you a {grade} grade ({descriptor}). Maintain this incredible trajectory!",
  ],
  improved5: [
    "Excellent progress! You improved by {dev}% from last term. Your dedication to {bestSubject} is clearly evident in your {grade} grade ({descriptor}). To reach even greater heights, please give more attention to {weakestSubject}. Keep soaring!",
    "Fantastic improvement! Rising by {dev}% demonstrates real commitment. Your {grade} grade in {bestSubject} reflects your growing excellence. Continue nurturing your strengths while working on {weakestSubject}.",
  ],
  improved2: [
    "Good improvement! You rose by {dev}% from last term. Your {grade} grade shows positive growth. Continue building on your strength in {bestSubject} while dedicating time to {weakestSubject}. Steady progress leads to remarkable success!",
    "Nice upward trend! A {dev}% improvement shows you are on the right path. Your {grade} grade in {bestSubject} is encouraging. Keep refining your approach, especially for {weakestSubject}.",
  ],
  consistent: [
    "Consistent performance this term with a {grade} grade ({descriptor}). You demonstrate steady capability in {bestSubject}. Let's set ambitious goals to elevate {weakestSubject} next term. Your reliability is a valuable asset!",
    "Steady and reliable! Your {grade} grade ({descriptor}) shows consistency. Your strength in {bestSubject} is clear. Channeling more energy into {weakestSubject} will create a more balanced academic profile.",
  ],
  dropped5: [
    "Your performance dropped by {dev}% from last term. Do not be discouraged — every accomplished learner faces challenges. Focus more on {weakestSubject} and seek guidance from your teacher. We have full confidence you will bounce back stronger!",
    "A slight dip of {dev}% this term, but setbacks are setups for comebacks. Your previous success in {bestSubject} proves your capability. Let's create a recovery plan for {weakestSubject}. You've got this!",
  ],
  dropped10: [
    "Your performance dropped by {dev}% from last term, which requires attention. Please dedicate more quality time to {weakestSubject} and revisit your study strategies. Your teachers and parents are here to support your recovery. We believe in your resilience!",
    "A decline of {dev}% is concerning, but not insurmountable. Your past performance in {bestSubject} shows you have the ability. Let's identify obstacles together and create a targeted improvement plan for {weakestSubject}.",
  ],
  droppedSevere: [
    "Your performance dropped significantly by {dev}% from last term. Urgent intervention is needed, particularly in {weakestSubject}. Please schedule a meeting with your class teacher to develop a comprehensive improvement strategy. Your potential is untapped — we are here to help you recover!",
    "A substantial decline of {dev}% demands immediate action. Your capability in {bestSubject} proves you can excel. Let's work together intensively on {weakestSubject}. With focused effort and support, remarkable recovery is absolutely possible!",
  ],
};

function seededRandom(seed: string): number {
  let hash = 0;
  for (let i = 0; i < seed.length; i++) {
    hash = ((hash << 5) - hash + seed.charCodeAt(i)) | 0;
  }
  return Math.abs(hash) / 2147483647;
}

export function generateUniqueAIComment(
  studentName: string,
  avgPct: number,
  deviation: number | null,
  bestSubject: string,
  weakestSubject: string,
  position: number | null,
  totalStudents: number,
  isNew: boolean,
  classData?: any,
  allSubjectResults?: SubjectResult[]
): string {
  // If we have full subject data, use the rich subject-specific generator
  if (allSubjectResults && allSubjectResults.length > 0) {
    return generateSubjectSpecificComment(
      studentName,
      allSubjectResults,
      avgPct,
      position,
      totalStudents,
      classData
    );
  }

  // Fallback to template-based generator
  const grade = calculateGradeForClass(avgPct, classData);
  const gradeLabel = gradeLabelForClass(avgPct, classData);
  const descriptor = grade.descriptor;

  const seed = `${studentName}-${avgPct.toFixed(1)}-${position}-${totalStudents}-${deviation || 0}`;
  const rand = seededRandom(seed);

  let templates: string[];

  if (position === 1 && totalStudents >= 3) {
    templates = COMMENT_TEMPLATES.top1;
  } else if (position === 2 && totalStudents >= 3) {
    templates = COMMENT_TEMPLATES.top2;
  } else if (position === 3 && totalStudents >= 3) {
    templates = COMMENT_TEMPLATES.top3;
  } else if (position && position <= 5 && totalStudents >= 5) {
    templates = COMMENT_TEMPLATES.top5;
  } else if (isNew || deviation === null) {
    templates = COMMENT_TEMPLATES.newStudent;
  } else if (deviation > 10) {
    templates = COMMENT_TEMPLATES.improved10;
  } else if (deviation > 5) {
    templates = COMMENT_TEMPLATES.improved5;
  } else if (deviation > 2) {
    templates = COMMENT_TEMPLATES.improved2;
  } else if (deviation >= -1) {
    templates = COMMENT_TEMPLATES.consistent;
  } else if (deviation >= -5) {
    templates = COMMENT_TEMPLATES.dropped5;
  } else if (deviation >= -10) {
    templates = COMMENT_TEMPLATES.dropped10;
  } else {
    templates = COMMENT_TEMPLATES.droppedSevere;
  }

  const template = templates[Math.floor(rand * templates.length)];

  return template
    .replace('{studentName}', studentName)
    .replace('{bestSubject}', bestSubject)
    .replace('{weakestSubject}', weakestSubject)
    .replace('{position}', String(position || 'N/A'))
    .replace('{total}', String(totalStudents))
    .replace('{dev}', deviation !== null ? Math.abs(deviation).toFixed(1) : '0')
    .replace('{grade}', gradeLabel)
    .replace('{descriptor}', descriptor)
    .replace('{avgPct}', avgPct.toFixed(1));
}

// ── Performance Trend Data and Graph Drawing ──────────────────────────────────
export interface PerformanceTrendRecord {
  percentage?: number | null;
  marks?: number | null;
  out_of?: number | null;
  term_id?: string | null;
  exam_id?: string | null;
  terms?: { name?: string | null; academic_year?: string | number | null } | null;
  school_exams?: { name?: string | null; type?: string | null; is_active?: boolean | null } | null;
  exam_name?: string | null;
}

const termOrder = (name: string): number => {
  const normalized = name.toLowerCase();
  if (/\b(term|trimester|semester)?\s*1\b/.test(normalized)) return 1;
  if (/\b(term|trimester|semester)?\s*2\b/.test(normalized)) return 2;
  if (/\b(term|trimester|semester)?\s*3\b/.test(normalized)) return 3;
  return 99;
};

/**
 * Groups a learner's result rows by distinct term and assessment, then orders
 * them chronologically. Older rows without an exam link still fall back to a
 * term-level point, so historic data remains visible in the graph.
 */
export function buildPerformanceTrend(records: PerformanceTrendRecord[]): { term: string; avg: number }[] {
  const groups = new Map<string, {
    label: string;
    year: number;
    term: number;
    firstIndex: number;
    total: number;
    totalMarks: number;
    totalOutOf: number;
    count: number;
  }>();

  records.forEach((record, index) => {
    // The active assessment is still being entered in many schools. Do not
    // let an incomplete/current assessment distort the exam comparison graph.
    if (record.school_exams?.is_active === true) return;
    const termName = String(record.terms?.name || '').trim();
    const yearText = String(record.terms?.academic_year || '').trim();
    const year = Number(yearText) || 0;
    const examName = String(record.school_exams?.name || record.exam_name || '').trim();
    const termKey = String(record.term_id || `${yearText}-${termName}`);
    const assessmentKey = String(record.exam_id || examName || 'term');
    const key = `${termKey}-${assessmentKey}`;
    const labelBase = [termName, yearText].filter(Boolean).join(' ');
    const label = examName
      ? `${examName}${labelBase ? ` · ${labelBase}` : ''}`
      : labelBase || 'Assessment';
    const percentage = record.percentage !== undefined && record.percentage !== null
      ? Number(record.percentage)
      : Number(record.out_of) > 0
        ? (Number(record.marks) || 0) / Number(record.out_of) * 100
        : 0;
    const safePercentage = Number.isFinite(percentage) ? Math.max(0, Math.min(100, percentage)) : 0;
    const marks = Number(record.marks);
    const outOf = Number(record.out_of);
    const existing = groups.get(key);
    if (existing) {
      existing.total += safePercentage;
      existing.totalMarks += Number.isFinite(marks) ? marks : safePercentage;
      existing.totalOutOf += Number.isFinite(outOf) && outOf > 0 ? outOf : 100;
      existing.count += 1;
      return;
    }
    groups.set(key, {
      label,
      year,
      term: termOrder(termName),
      firstIndex: index,
      total: safePercentage,
      totalMarks: Number.isFinite(marks) ? marks : safePercentage,
      totalOutOf: Number.isFinite(outOf) && outOf > 0 ? outOf : 100,
      count: 1,
    });
  });

  return Array.from(groups.values())
    .sort((a, b) => a.year - b.year || a.term - b.term || a.firstIndex - b.firstIndex)
    .map((group) => ({
      term: group.label,
      avg: group.count > 0 ? group.total / group.count : 0,
      totalMarks: group.totalMarks,
      maxTotalMarks: group.totalOutOf,
    }));
}

export function drawTrendGraph(
  doc: jsPDF,
  trendData: { term: string; avg: number }[],
  x: number,
  y: number,
  width: number,
  height: number,
  _band: SchoolLevelBand
): number {
  if (!trendData.length || width <= 20 || height <= 12) return y;
  // Compact report cards must keep the chart and every following section on
  // the same A4 page. Move the chart into the safe area instead of letting it
  // render below the page or disappear behind the footer.
  const graphY = ensureReportCardSpace(doc, y, height + 1);
  const hasTotals = trendData.some((item: any) => Number.isFinite(Number(item.totalMarks)));
  const safeValues = trendData.map((item: any) => hasTotals
    ? Math.max(0, Number(item.totalMarks) || 0)
    : Math.max(0, Math.min(100, Number(item.avg) || 0)));
  const maxValue = hasTotals
    ? Math.max(1, ...trendData.map((item: any) => Number(item.maxTotalMarks) || Number(item.totalMarks) || 0))
    : 100;
  const left = x + 18;
  const top = graphY + 8;
  const graphWidth = Math.max(20, width - 24);
  const graphHeight = Math.max(12, height - 22);
  doc.setDrawColor(210, 210, 210);
  doc.setFillColor(250, 250, 252);
  doc.roundedRect(x, graphY, width, height, 2, 2, 'FD');
  doc.setFontSize(pdfFontSize(doc, 6.5));
  doc.setTextColor(90, 90, 90);
  doc.setFont('helvetica', 'bold');
  doc.text(hasTotals ? 'Exam Comparison — Total Marks' : 'Exam Comparison — Percentage', x + 4, graphY + 6);
  doc.setFont('helvetica', 'normal');
  const ticks = hasTotals ? [0, Math.round(maxValue / 2), Math.round(maxValue)] : [0, 50, 100];
  ticks.forEach((value) => {
    const gridY = top + graphHeight - (value / maxValue) * graphHeight;
    doc.setDrawColor(232, 232, 232);
    doc.line(left, gridY, left + graphWidth, gridY);
    doc.setTextColor(120, 120, 120);
    doc.text(String(value), x + 3, gridY + 2);
  });
  const slot = graphWidth / Math.max(1, safeValues.length);
  const colors = [[37, 99, 235], [245, 158, 11], [34, 197, 94], [168, 85, 247]];
  safeValues.forEach((value, index) => {
    const barWidth = Math.min(18, slot * 0.62);
    const barHeight = (value / maxValue) * graphHeight;
    const barX = left + slot * index + (slot - barWidth) / 2;
    const barY = top + graphHeight - barHeight;
    doc.setFillColor(...(colors[index % colors.length] as [number, number, number]));
    doc.rect(barX, barY, barWidth, barHeight, 'F');
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(pdfFontSize(doc, 6.5));
    doc.setTextColor(35, 45, 65);
    doc.text(hasTotals ? String(Math.round(value)) : `${value.toFixed(0)}%`, barX + barWidth / 2, Math.max(top + 4, barY - 1.5), { align: 'center' });
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(90, 90, 90);
    doc.text(String(trendData[index].term || '').slice(0, 14), barX + barWidth / 2, graphY + height - 5, { align: 'center' });
  });
  return graphY + height;
}

// ── Add Logo to PDF ──────────────────────────────────────────────────────────
// Helper to compress and convert image to JPEG data URL
async function compressImage(src: string, maxWidth: number = 400, quality: number = 0.7): Promise<string> {
  return new Promise((resolve, reject) => {
    const timeout = setTimeout(() => reject(new Error('Resource load timeout')), 12000);
    const img = new Image();
    // Setting crossOrigin on data URLs can make some mobile browsers reject an otherwise valid image.
    if (!src.startsWith('data:') && !src.startsWith('blob:')) img.crossOrigin = 'anonymous';
    img.onload = () => {
      clearTimeout(timeout);
      const sourceWidth = img.naturalWidth || img.width;
      const sourceHeight = img.naturalHeight || img.height;
      if (!sourceWidth || !sourceHeight) {
        reject(new Error('Image has no readable dimensions'));
        return;
      }
      const scale = Math.min(1, maxWidth / sourceWidth);
      const width = Math.max(1, Math.round(sourceWidth * scale));
      const height = Math.max(1, Math.round(sourceHeight * scale));
      const canvas = document.createElement('canvas');
      canvas.width = width;
      canvas.height = height;
      const ctx = canvas.getContext('2d');
      if (!ctx) {
        reject(new Error('Canvas is unavailable'));
        return;
      }
      ctx.fillStyle = '#FFFFFF';
      ctx.fillRect(0, 0, width, height);
      ctx.drawImage(img, 0, 0, width, height);
      resolve(canvas.toDataURL('image/jpeg', quality));
    };
    img.onerror = () => {
      clearTimeout(timeout);
      reject(new Error('Resource load failed'));
    };
    img.src = src;
  });
}

async function compressSquareImage(src: string, maxSize: number = 800, quality: number = 0.92): Promise<string> {
  return new Promise((resolve, reject) => {
    const timeout = setTimeout(() => reject(new Error('Photo load timeout')), 12000);
    const img = new Image();
    if (!src.startsWith('data:') && !src.startsWith('blob:')) img.crossOrigin = 'anonymous';
    img.onload = () => {
      clearTimeout(timeout);
      const sourceWidth = img.naturalWidth || img.width;
      const sourceHeight = img.naturalHeight || img.height;
      const side = Math.min(sourceWidth, sourceHeight);
      if (!side) {
        reject(new Error('Photo has no readable dimensions'));
        return;
      }
      const outputSize = Math.max(1, Math.min(maxSize, side));
      const canvas = document.createElement('canvas');
      canvas.width = outputSize;
      canvas.height = outputSize;
      const ctx = canvas.getContext('2d');
      if (!ctx) {
        reject(new Error('Canvas is unavailable'));
        return;
      }
      ctx.fillStyle = '#FFFFFF';
      ctx.fillRect(0, 0, outputSize, outputSize);
      const sx = (sourceWidth - side) / 2;
      const sy = (sourceHeight - side) / 2;
      ctx.drawImage(img, sx, sy, side, side, 0, 0, outputSize, outputSize);
      resolve(canvas.toDataURL('image/jpeg', quality));
    };
    img.onerror = () => {
      clearTimeout(timeout);
      reject(new Error('Photo resource failed to load'));
    };
    img.src = src;
  });
}

// Image cache to prevent redundant processing and bloat in bulk generation
const imageCache: Record<string, string> = {};

export async function addLogoToPDF(
  doc: jsPDF,
  logoUrl: string | null | undefined,
  x: number,
  y: number,
  maxWidth: number,
  maxHeight: number
): Promise<boolean> {
  if (!logoUrl) return false;
  try {
    let dataUrl = imageCache[logoUrl];
    if (!dataUrl) {
      dataUrl = await compressImage(logoUrl, 300, 0.7);
      imageCache[logoUrl] = dataUrl;
    }
    doc.addImage(dataUrl, 'JPEG', x, y, maxWidth, maxHeight, undefined, 'FAST');
    return true;
  } catch (err) {
    console.error('Logo add error:', err);
    return false;
  }
}

/** Place the school's logo lightly behind the report-card body content. */
export async function addLogoWatermarkToPDF(
  doc: jsPDF,
  logoUrl: string | null | undefined,
  options: { opacity?: number; size?: number; y?: number } = {},
): Promise<boolean> {
  if (!logoUrl) return false;
  try {
    let dataUrl = imageCache[logoUrl];
    if (!dataUrl) {
      dataUrl = await compressImage(logoUrl, 500, 0.82);
      imageCache[logoUrl] = dataUrl;
    }
    const size = options.size ?? 118;
    const x = (doc.internal.pageSize.getWidth() - size) / 2;
    const y = options.y ?? 88;
    const opacity = Math.max(0.03, Math.min(0.18, options.opacity ?? 0.08));
    const pdfDoc = doc as any;
    if (typeof pdfDoc.saveGraphicsState === 'function') pdfDoc.saveGraphicsState();
    if (typeof pdfDoc.setGState === 'function' && typeof pdfDoc.GState === 'function') {
      pdfDoc.setGState(new pdfDoc.GState({ opacity }));
    }
    doc.addImage(dataUrl, 'JPEG', x, y, size, size, undefined, 'FAST');
    if (typeof pdfDoc.restoreGraphicsState === 'function') pdfDoc.restoreGraphicsState();
    return true;
  } catch (err) {
    console.error('Logo watermark error:', err);
    return false;
  }
}

// ── Corner identity fallbacks ──────────────────────────────────────────────────
export function drawLogoPlaceholder(
  doc: jsPDF,
  label: string,
  x: number,
  y: number,
  size: number,
) {
  doc.setFillColor(255, 255, 255);
  doc.setDrawColor(106, 27, 154);
  doc.setLineWidth(0.6);
  doc.roundedRect(x, y, size, size, 2, 2, 'FD');
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(Math.max(pdfFontSize(doc, 8), pdfFontSize(doc, size * 0.34)));
  doc.setTextColor(106, 27, 154);
  doc.text(label, x + size / 2, y + size / 2 + size * 0.12, { align: 'center' });
  doc.setTextColor(0, 0, 0);
}

export function drawStudentPhotoPlaceholder(
  doc: jsPDF,
  studentName: string,
  x: number,
  y: number,
  size: number
) {
  const initials = studentName
    .trim()
    .split(/\s+/)
    .filter(Boolean)
    .slice(0, 2)
    .map(part => part[0]?.toUpperCase() || '')
    .join('') || 'ST';
  doc.setFillColor(232, 234, 246);
  doc.setDrawColor(106, 27, 154);
  doc.setLineWidth(0.6);
  doc.roundedRect(x, y, size, size, 2, 2, 'FD');
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(Math.max(pdfFontSize(doc, 9), pdfFontSize(doc, size * 0.42)));
  doc.setTextColor(106, 27, 154);
  doc.text(initials, x + size / 2, y + size / 2 + size * 0.14, { align: 'center' });
  doc.setTextColor(0, 0, 0);
}

export async function addStudentPhotoToPDF(
  doc: jsPDF,
  photoUrl: string | null | undefined,
  x: number,
  y: number,
  size: number
): Promise<boolean> {
  if (!photoUrl) return false;
  try {
    let dataUrl = imageCache[photoUrl];
    if (!dataUrl) {
      // Crop to a square before placing it, preserving the learner’s face and avoiding distortion.
      dataUrl = await compressSquareImage(photoUrl, 800, 0.92);
      imageCache[photoUrl] = dataUrl;
    }

    doc.setDrawColor(255, 255, 255);
    doc.setLineWidth(1);
    doc.rect(x - 0.5, y - 0.5, size + 1, size + 1, 'D');
    doc.addImage(dataUrl, 'JPEG', x, y, size, size, undefined, 'FAST');
    doc.setDrawColor(200, 200, 200);
    doc.setLineWidth(0.1);
    doc.rect(x - 0.6, y - 0.6, size + 1.2, size + 1.2, 'D');
    return true;
  } catch (err) {
    console.error('Photo add error:', err);
    return false;
  }
}

// ── Draw Report Header ───────────────────────────────────────────────────────
export async function drawReportHeader(
  doc: jsPDF,
  school: SchoolInfo,
  learner?: ReportCardLearnerIdentity,
) {
  doc.setFillColor(255, 255, 255);
  doc.rect(0, 0, 210, HDR_H, 'F');
  doc.setDrawColor(47, 157, 190);
  doc.setLineWidth(0.6);
  doc.rect(2.5, 2.5, 205, 292, 'S');

  // Keep both identity images in matching 22mm squares at the same height.
  // The school logo is always on the left and the learner photo/initials on the right.
  const logoAdded = await addLogoToPDF(
    doc,
    school.logo_url || '/logo.png',
    15,
    5,
    27,
    22,
  );
  if (!logoAdded) drawLogoPlaceholder(doc, 'ZA', 15, 5, 22);
  // Always reserve a clearly visible passport-photo space, even when no image
  // has been uploaded yet. This prevents the learner identity area appearing
  // incomplete and leaves a predictable place for a future passport photo.
  const photoX = 174;
  const photoY = 4;
  const photoSize = 22;
  const photoAdded = learner?.photoUrl
    ? await addStudentPhotoToPDF(doc, learner.photoUrl, photoX, photoY, photoSize)
    : false;
  if (!photoAdded) {
    doc.setDrawColor(120, 145, 155); doc.setLineWidth(0.35); doc.rect(photoX, photoY, photoSize, photoSize, 'D');
    doc.setFont('helvetica', 'bold'); doc.setFontSize(pdfFontSize(doc, 5.2)); doc.setTextColor(90, 105, 115);
    doc.text('PASSPORT', photoX + photoSize / 2, photoY + 9, { align: 'center' });
    doc.text('PHOTO', photoX + photoSize / 2, photoY + 14, { align: 'center' });
  }

  // Center the school identity in the clear space between the logo and passport box.
  const centerX = 105;
  doc.setTextColor(26, 35, 126);
  doc.setFontSize(pdfFontSize(doc, COMPACT_MODE ? 13 : 16));
  doc.setFont('helvetica', 'bold');
  doc.text(school.name || 'School Name', centerX, 10, { align: 'center', maxWidth: 125 });
  doc.setFontSize(pdfFontSize(doc, COMPACT_MODE ? 10 : 12));
  const contactLine = [school.phone, school.email].filter(Boolean).join(' | ');
  if (contactLine) {
    doc.setFontSize(pdfFontSize(doc, COMPACT_MODE ? 8 : 9));
    doc.text(contactLine, centerX, 16, { align: 'center', maxWidth: 125 });
  }
  if (school.address) {
    doc.setFontSize(pdfFontSize(doc, COMPACT_MODE ? 7.5 : 8.5));
    doc.text(school.address, centerX, 21, { align: 'center', maxWidth: 125 });
  }
  doc.setFontSize(pdfFontSize(doc, COMPACT_MODE ? 7.5 : 8.5));
  if (school.motto) doc.text(school.motto, centerX, 25, { align: 'center', maxWidth: 125 });
  const reportLine = [school.report_class, school.report_term, school.report_year].filter(Boolean).join(' — ');
  if (reportLine) doc.text(reportLine, centerX, 28.5, { align: 'center', maxWidth: 125 });
  doc.setDrawColor(47, 157, 190); doc.setLineWidth(0.35); doc.line(6, HDR_H + 1, 204, HDR_H + 1);
  await addLogoWatermarkToPDF(doc, school.logo_url);
}

export function getLearnerLoginUrl(assessmentNumber?: string | null, origin?: string): string {
  const baseOrigin = origin
    || (typeof window !== 'undefined' ? window.location.origin : 'https://zamifu.company');
  const url = new URL('/auth/login', baseOrigin);
  const normalizedAssessment = String(assessmentNumber || '').trim().toUpperCase();
  if (normalizedAssessment) url.searchParams.set('assessment', normalizedAssessment);
  return url.toString();
}

async function addLearnerLoginQrToPDF(
  doc: jsPDF,
  y: number,
  options: ReportCardQrOptions = {},
): Promise<void> {
  const qrSize = 20;
  const qrX = 169;
  const loginUrl = options.loginUrl || getLearnerLoginUrl(options.assessmentNumber);
  const qrDataUrl = await QRCode.toDataURL(loginUrl, {
    errorCorrectionLevel: 'M',
    margin: 1,
    width: 240,
  });
  doc.addImage(qrDataUrl, 'PNG', qrX, y, qrSize, qrSize, undefined, 'FAST');
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(pdfFontSize(doc, COMPACT_MODE ? 5 : 5.5));
  doc.setTextColor(70, 70, 80);
  const caption = doc.splitTextToSize(
    'Scan to view your results. Log in with your Assessment Number.',
    32,
  );
  doc.text(caption, qrX + qrSize / 2, y + qrSize + 2.5, { align: 'center' });
  doc.setTextColor(0, 0, 0);
}

// ── Add Signatures to PDF ────────────────────────────────────────────────────
export async function addSignaturesToPDF(
  doc: jsPDF,
  signatures: SignatureInfo,
  y: number,
  schoolInfo?: SchoolInfo,
  qrOptions: ReportCardQrOptions = {},
) {
  // The caller's y is retained for API compatibility, but the block is
  // always bottom-anchored. This makes the reservation deterministic and
  // prevents a late QR/signature block from covering the comment.
  const signatureLayout = getReportCardSignatureLayout(schoolInfo, qrOptions);
  const hasQr = signatureLayout.hasQr;
  const sigBlockH = signatureLayout.coreHeight;
  const sigImgH = COMPACT_MODE ? 8 : 16;
  const sigImgY = COMPACT_MODE ? 0.5 : 3;
  const sigLabelY = COMPACT_MODE ? 9 : 22;
  const calendarNoticeLines = signatureLayout.calendarNoticeLines;
  y = getReportCardSignatureZoneTop(doc, schoolInfo, qrOptions);
  const hasPrincipalSig = signatures.principal_signature_url && signatures.principal_signature_url.startsWith('data:');
  const hasTeacherSig = signatures.teacher_signature_url && signatures.teacher_signature_url.startsWith('data:');
  doc.setFontSize(pdfFontSize(doc, COMPACT_MODE ? 6 : 7));
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(60, 60, 70);
  if (hasTeacherSig || hasPrincipalSig) {
    if (!COMPACT_MODE) doc.text('DIGITAL SIGNATURES', 14, y);
    if (hasTeacherSig) {
      try {
        let sigUrl = imageCache[signatures.teacher_signature_url!];
        if (!sigUrl) {
          sigUrl = await compressImage(signatures.teacher_signature_url!, 200, 0.6);
          imageCache[signatures.teacher_signature_url!] = sigUrl;
        }
        doc.addImage(sigUrl, 'JPEG', 14, y + sigImgY, 40, sigImgH, undefined, 'FAST');
      } catch {
        doc.setDrawColor(150, 150, 155);
        doc.line(14, y + sigLabelY - 2, 56, y + sigLabelY - 2);
      }
    } else {
      doc.setDrawColor(150, 150, 155);
      doc.line(14, y + sigLabelY - 2, 56, y + sigLabelY - 2);
    }
    doc.setFontSize(pdfFontSize(doc, COMPACT_MODE ? 5.5 : 6));
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(100, 100, 110);
    doc.text('Class Teacher Signature', 14, y + sigLabelY);
    if (hasPrincipalSig) {
      try {
        let sigUrl = imageCache[signatures.principal_signature_url!];
        if (!sigUrl) {
          sigUrl = await compressImage(signatures.principal_signature_url!, 200, 0.6);
          imageCache[signatures.principal_signature_url!] = sigUrl;
        }
        doc.addImage(sigUrl, 'JPEG', 118, y + sigImgY, 40, sigImgH, undefined, 'FAST');
      } catch {
        doc.setDrawColor(150, 150, 155);
        doc.line(118, y + sigLabelY - 2, 160, y + sigLabelY - 2);
      }
    } else {
      doc.setDrawColor(150, 150, 155);
      doc.line(118, y + sigLabelY - 2, 160, y + sigLabelY - 2);
    }
    doc.setFontSize(pdfFontSize(doc, COMPACT_MODE ? 5.5 : 6));
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(100, 100, 110);
    doc.text('Principal Signature', 118, y + sigLabelY);
  } else {
    doc.setDrawColor(150, 150, 155);
    doc.line(14, y + (COMPACT_MODE ? 9 : 12), 75, y + (COMPACT_MODE ? 9 : 12));
    doc.line(118, y + (COMPACT_MODE ? 9 : 12), 181, y + (COMPACT_MODE ? 9 : 12));
    doc.setFontSize(pdfFontSize(doc, COMPACT_MODE ? 6 : 7));
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(80, 80, 85);
    doc.text('Class Teacher Signature', 14, y + (COMPACT_MODE ? 15 : 18));
    doc.text('Principal Signature', 118, y + (COMPACT_MODE ? 15 : 18));
  }
  // Date
  doc.setFontSize(pdfFontSize(doc, COMPACT_MODE ? 6 : 7));
  doc.setTextColor(80, 80, 85);
  doc.text(`Date: ${new Date().toLocaleDateString()}`, 14, y + (COMPACT_MODE ? 12 : 27));
  // School stamp area
  doc.setDrawColor(180, 180, 185);
  doc.setLineDashPattern([2, 2], 0);
  doc.rect(118, y + sigImgY, 32, sigImgH + 2);
  doc.setLineDashPattern([], 0);
  doc.setFontSize(pdfFontSize(doc, 5.5));
  doc.setTextColor(150, 150, 155);
  doc.text('OFFICIAL STAMP', 134, y + sigImgY + sigImgH / 2, { align: 'center' });

  if (hasQr) {
    try {
      await addLearnerLoginQrToPDF(doc, y, qrOptions);
    } catch (error) {
      console.warn('Learner login QR could not be added to report card:', error);
    }
  }

  if (calendarNoticeLines.length > 0) {
    doc.setTextColor(0, 102, 102);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(pdfFontSize(doc, COMPACT_MODE ? 7.2 : 8));
    doc.text(calendarNoticeLines, 14, y + sigBlockH + (COMPACT_MODE ? 4 : 5), { maxWidth: 180 });
    doc.setTextColor(0, 0, 0);
    return y + sigBlockH + (COMPACT_MODE ? 12 : 16);
  }

  return y + sigBlockH;
}

// ── Draw Footer ──────────────────────────────────────────────────────────────
export function drawReportFooter(doc: jsPDF) {
  const pageHeight = doc.internal.pageSize.getHeight();
  doc.setFontSize(pdfFontSize(doc, 8));
  doc.setTextColor(150, 150, 150);
  doc.setFont('helvetica', 'normal');
  doc.text('Zamifu Analytics School Management System | Support: zamifu@zamifu.company', 105, pageHeight - 6, { align: 'center' });
}

// ── Draw Student Info ────────────────────────────────────────────────────────
export function drawStudentInfo(
  doc: jsPDF,
  studentName: string,
  admissionNo: string,
  className: string,
  termName: string,
  academicYear: string,
  position: string,
  y: number = 38,
  assessmentName?: string,
  assessmentNumber?: string,
  positionDetails?: { classPosition?: string; streamPosition?: string; totalMarks?: string; totalPoints?: string; overallDeviation?: string; showPoints?: boolean; pathway?: string; track?: string; overallGrade?: string; showPathway?: boolean; is844?: boolean }
) {
  const fs = pdfFontSize(doc, COMPACT_MODE ? 6.8 : 8);
  const showPoints = positionDetails?.showPoints !== false;
  const standardRows: string[][] = [
    ["Learner's Name", studentName || '—', 'Admission No.', admissionNo || '—', 'Assessment Name', assessmentName || `${termName} ${academicYear}`],
    ['Assessment No.', assessmentNumber || '—', 'Total Marks', positionDetails?.totalMarks || '—', showPoints ? 'Total Points' : '', showPoints ? (positionDetails?.totalPoints || '—') : ''],
    ['Class Position', positionDetails?.classPosition || position || '—', ...(positionDetails?.streamPosition ? ['Stream Position', positionDetails.streamPosition, 'Date', new Date().toLocaleDateString()] : ['Class / Stream', className || '—', 'Date', new Date().toLocaleDateString()])],
  ];
  const showPathway = positionDetails?.showPathway || positionDetails?.is844;
  const rows: string[][] = showPathway ? [
    ["Learner's Name", studentName || '—', 'Admission No.', admissionNo || '—', 'Assessment No.', assessmentNumber || '—'],
    ['Class', className || '—', 'Pathway', positionDetails?.pathway || '—', 'Track', positionDetails?.track || '—'],
    ['Total Marks', positionDetails?.totalMarks || '—', showPoints ? 'Total Points' : '', showPoints ? (positionDetails?.totalPoints || '—') : '', positionDetails?.is844 ? 'Overall Grade' : 'Overall Level', positionDetails?.overallGrade || '—'],
    ['Class Position', positionDetails?.classPosition || position || '—', 'Stream Position', positionDetails?.streamPosition || '—', 'Date', new Date().toLocaleDateString()],
  ] : standardRows;
  const widths = [27, 43, 27, 32, 27, 26];
  doc.setFontSize(fs); doc.setFont('helvetica', 'normal');
  rows.forEach((row, rowIndex) => {
    let cursor = 10;
    const rowY = y - 7 + rowIndex * 5.8;
    row.forEach((value, colIndex) => {
      const w = widths[colIndex];
      doc.setFillColor(colIndex % 2 === 0 ? 226 : 255, colIndex % 2 === 0 ? 239 : 255, colIndex % 2 === 0 ? 247 : 255);
      doc.setDrawColor(130, 180, 190); doc.rect(cursor, rowY, w, 5.8, 'FD');
      doc.setTextColor(colIndex % 2 === 0 ? 26 : 35, colIndex % 2 === 0 ? 55 : 45, colIndex % 2 === 0 ? 90 : 65);
      doc.setFont('helvetica', colIndex % 2 === 0 ? 'bold' : 'normal');
      doc.text(String(value).slice(0, 35), cursor + 1.3, rowY + 3.8);
      cursor += w;
    });
  });
  if (positionDetails?.overallDeviation) {
    const value = positionDetails.overallDeviation;
    doc.setFont('helvetica', 'bold'); doc.setFontSize(pdfFontSize(doc, 7));
    doc.setTextColor(value.startsWith('-') ? 190 : value === '—' ? 100 : 22, value.startsWith('-') ? 45 : value === '—' ? 100 : 128, value.startsWith('-') ? 45 : value === '—' ? 100 : 65);
    doc.text(`Overall Deviation: ${value}`, 10, y + 12.8);
    doc.setTextColor(0, 0, 0);
  }
}

// ── Draw Results Table ───────────────────────────────────────────────────────
export function drawResultsTable(
  doc: jsPDF,
  results: any[],
  classData: any,
  startY: number,
  options: ReportCardTableOptions = {}
): number {
  startY = ensureReportCardSpace(doc, startY, 24);
  const sorted = sortResultsBySubject(results);
  const isPrimary = getSchoolLevelBand(classData) === 'primary';
  const is844 = is844Curriculum(classData);
  const sevenSubjectRanking = usesSevenSubjectRanking(classData);
  const pointsMax = gradePointsMaxForClass(classData);
  const showStream = options.showStreamPosition === true;
  const showDeviation = options.showDeviation !== false;
  const assessmentColumns = options.assessmentColumns || [];
  const deviationHead = showDeviation ? ['Deviation (%)'] : [];
  const assessmentCellCount = assessmentColumns.length * 3;
  const areaLabel = is844 ? 'Subject' : 'Learning Area';
  const levelLabel = is844 ? 'Grade' : 'Performance Level';
  const tableHead = assessmentColumns.length
    ? ['No.', areaLabel, ...assessmentColumns.flatMap(column => [`${column.label}\nMarks`, `${column.label}\nPts`, `${column.label}\n${is844 ? 'Grade' : 'Level'}`]), 'Average (%)', ...deviationHead, ...(pointsMax > 0 ? [`Points (Out of ${pointsMax})`] : []), levelLabel, ...(showStream ? ['Stream Position'] : []), 'Class Position', "Teacher's Name", "Teacher's Comment"]
    : ['No.', areaLabel, 'Marks (/100)', ...deviationHead, ...(pointsMax > 0 ? [`Points (Out of ${pointsMax})`] : []), levelLabel, ...(showStream ? ['Stream Position'] : []), 'Class Position', "Teacher's Name", "Teacher's Comment"];
  const tableBody = sorted.map((r, i) => {
    const excluded = isExcludedResult(r);
    const pct = excluded ? 0 : getPercentage(r);
    const grading = excluded ? null : gradeFromPercentage(pct, classData);
    const subjectName = r.subjects?.name === 'Creative Arts' ? 'C-Arts' : (r.subjects?.name || 'N/A');
    const previous = r.previousPercentage === null || r.previousPercentage === undefined ? null : Number(r.previousPercentage);
    const deviation = excluded || previous === null ? '—' : `${pct - previous >= 0 ? '+' : ''}${(pct - previous).toFixed(1)}%`;
    const position = r.classPosition ? `${r.classPosition}/${r.classTotal || '—'}` : '—';
    const streamPosition = r.streamPosition ? `${r.streamPosition}/${r.streamTotal || '—'}` : '—';
    const row: any[] = [i + 1, subjectName];
    if (assessmentColumns.length) {
      assessmentColumns.forEach((column) => {
        const value = r.assessmentValues?.[column.id];
        if (value == null) {
          row.push('—', '—', '—');
          return;
        }
        const metric = typeof value === 'object'
          ? value
          : { marks: Number(value), outOf: 100, percentage: Number(value) };
        const examGrade = calculateGradeForClass(Number(metric.percentage), classData);
        const examLevel = 'subLevel' in examGrade ? examGrade.subLevel : examGrade.grade;
        const marksLabel = Number(metric.outOf) === 100
          ? Number(metric.marks).toFixed(0)
          : `${Number(metric.marks).toFixed(0)}/${Number(metric.outOf).toFixed(0)}`;
        row.push(marksLabel, pointsMax > 0 ? (examGrade.points ?? '—') : '—', examLevel || '—');
      });
      row.push(excluded ? 'X' : `${pct.toFixed(0)}%`);
      if (showDeviation) row.push(deviation);
    } else {
      row.push(excluded ? 'X' : `${pct.toFixed(0)}/100`);
      if (showDeviation) row.push(deviation);
    }
    if (pointsMax > 0) row.push(grading?.points ?? '—');
    row.push(excluded ? 'X' : grading?.grade || '—');
    if (showStream) row.push(streamPosition);
    row.push(position, r.teacherName || '—', r.teacherComment || '—');
    return row;
  });
  const includedRows = sorted.filter((row) => !isExcludedResult(row));
  const totalMarks = options.rankingDetails?.totalMarks ?? includedRows.reduce((sum, row) => sum + getPercentage(row), 0);
  const totalMarksLabel = `${Math.round(totalMarks)} / ${sevenSubjectRanking ? 700 : includedRows.length * 100}`;
  const totalPoints = options.rankingDetails?.totalPoints ?? includedRows.reduce((sum, row) => sum + (Number(gradeFromPercentage(getPercentage(row), classData).points) || 0), 0);
  const totalMarksRow = new Array(tableHead.length).fill('');
  const averageIndex = 2 + assessmentCellCount;
  totalMarksRow[1] = 'TOTAL MARKS'; totalMarksRow[assessmentColumns.length ? averageIndex : 2] = totalMarksLabel;
  tableBody.push(totalMarksRow);
  if (pointsMax > 0) {
    const totalPointsRow = new Array(tableHead.length).fill('');
    totalPointsRow[1] = 'TOTAL POINTS'; totalPointsRow[assessmentColumns.length ? averageIndex + 1 + (showDeviation ? 1 : 0) : 3 + (showDeviation ? 1 : 0)] = `${totalPoints || '—'} / ${sevenSubjectRanking ? 56 : includedRows.length * pointsMax}`;
    tableBody.push(totalPointsRow);
  }
  doc.setFillColor(228, 246, 225); doc.setDrawColor(137, 185, 142);
  doc.rect(9, startY - 6.5, 192, 6.5, 'FD');
  doc.setFont('helvetica', 'bold'); doc.setFontSize(pdfFontSize(doc, 8)); doc.setTextColor(26, 75, 92);
  doc.text('Learning Area Performance', 11, startY - 2.1);
  const combinedColumnStyles: Record<number, any> = {};
  if (assessmentColumns.length) {
    combinedColumnStyles[0] = { cellWidth: 7 };
    combinedColumnStyles[1] = { cellWidth: 23, fontStyle: 'bold', halign: 'left' };
    const metricWidth = Math.max(5, Math.min(10, 62 / assessmentCellCount));
    for (let index = 0; index < assessmentCellCount; index += 1) combinedColumnStyles[index + 2] = { cellWidth: metricWidth };
    let nextIndex = averageIndex;
    combinedColumnStyles[nextIndex] = { cellWidth: 10 }; nextIndex += 1;
    if (showDeviation) { combinedColumnStyles[nextIndex] = { cellWidth: 9 }; nextIndex += 1; }
    if (!isPrimary) { combinedColumnStyles[nextIndex] = { cellWidth: 9 }; nextIndex += 1; }
    combinedColumnStyles[nextIndex] = { cellWidth: 11 }; nextIndex += 1;
    if (showStream) { combinedColumnStyles[nextIndex] = { cellWidth: 10 }; nextIndex += 1; }
    combinedColumnStyles[nextIndex] = { cellWidth: 10 }; nextIndex += 1;
    combinedColumnStyles[nextIndex] = { cellWidth: 14, halign: 'left' }; nextIndex += 1;
    const assignedWidth = Object.values(combinedColumnStyles).reduce((sum: number, style: any) => sum + Number(style.cellWidth || 0), 0);
    combinedColumnStyles[nextIndex] = { cellWidth: Math.max(20, 192 - assignedWidth), halign: 'left' };
  }
  autoTable(doc, {
    startY,
    head: [tableHead],
    body: tableBody,
    pageBreak: COMPACT_MODE ? 'avoid' : 'auto',
    rowPageBreak: 'avoid',
    styles: { fontSize: pdfFontSize(doc, COMPACT_MODE ? 5.2 : 6.8), cellPadding: COMPACT_MODE ? 0.45 : 1, overflow: 'linebreak', valign: 'middle', halign: 'center' },
    headStyles: { fillColor: [223, 242, 216], textColor: [26, 35, 126], fontSize: pdfFontSize(doc, COMPACT_MODE ? 5.3 : 7), cellPadding: 0.55, halign: 'center' },
    alternateRowStyles: { fillColor: [244, 250, 239] }, margin: { left: 9, right: 9 },
    tableLineColor: [74, 112, 117], tableLineWidth: 0.45,
    columnStyles: assessmentColumns.length
      ? combinedColumnStyles
      : isPrimary
      ? (showStream
        ? { 0: { cellWidth: 7 }, 1: { cellWidth: 24, fontStyle: 'bold', halign: 'left' }, 2: { cellWidth: 16 }, ...(showDeviation ? { 3: { cellWidth: 15 } } : {}), 4: { cellWidth: 17 }, 5: { cellWidth: 15 }, 6: { cellWidth: 15 }, 7: { cellWidth: 21, halign: 'left' }, 8: { cellWidth: 62, halign: 'left' } }
        : { 0: { cellWidth: 7 }, 1: { cellWidth: 25, fontStyle: 'bold', halign: 'left' }, 2: { cellWidth: 18 }, ...(showDeviation ? { 3: { cellWidth: 16 } } : {}), 4: { cellWidth: 17 }, 5: { cellWidth: 16 }, 6: { cellWidth: 22, halign: 'left' }, 7: { cellWidth: 71, halign: 'left' } })
      : (showStream
        ? { 0: { cellWidth: 7 }, 1: { cellWidth: 22, fontStyle: 'bold', halign: 'left' }, 2: { cellWidth: 15 }, ...(showDeviation ? { 3: { cellWidth: 14 } } : {}), 4: { cellWidth: 13 }, 5: { cellWidth: 16 }, 6: { cellWidth: 15 }, 7: { cellWidth: 15, halign: 'left' }, 8: { cellWidth: 20 }, 9: { cellWidth: 55, halign: 'left' } }
        : { 0: { cellWidth: 7 }, 1: { cellWidth: 23, fontStyle: 'bold', halign: 'left' }, 2: { cellWidth: 17 }, ...(showDeviation ? { 3: { cellWidth: 16 } } : {}), 4: { cellWidth: 15 }, 5: { cellWidth: 17 }, 6: { cellWidth: 15, halign: 'left' }, 7: { cellWidth: 22 }, 8: { cellWidth: 60, halign: 'left' } }),
    didParseCell: (data: any) => {
      const teacherIndex = tableHead.indexOf("Teacher's Name");
      if (data.column.index === teacherIndex) data.cell.styles.halign = 'left';
      if (data.section !== 'body') return;
      const value = String(data.cell.raw ?? '');
      const deviationIndex = tableHead.indexOf('Deviation (%)');
      if (data.column.index === deviationIndex && value !== '—') {
        data.cell.styles.textColor = value.startsWith('+') ? [22, 128, 65] : value.startsWith('-') ? [190, 45, 45] : [100, 100, 100];
        data.cell.styles.fontStyle = 'bold';
      }
    },
    didDrawCell: (data: any) => {
      if (data.section === 'body') {
        doc.setDrawColor(95, 125, 130);
        doc.setLineWidth(0.28);
        doc.line(data.cell.x, data.cell.y + data.cell.height, data.cell.x + data.cell.width, data.cell.y + data.cell.height);
      }
    },
  });
  return (doc as any).lastAutoTable.finalY;
}

// ── Draw Pathway Performance ──────────────────────────────────────────────────
export function drawPathwayPerformance(
  doc: jsPDF,
  results: any[],
  startY: number,
): number {
  const pathwayRows = calculatePathwayPerformance(results);
  doc.setFontSize(pdfFontSize(doc, COMPACT_MODE ? 9 : 10)); doc.setFont('helvetica', 'bold'); doc.setTextColor(26, 35, 126);
  doc.text('Pathway Performance Profile', 14, startY + (COMPACT_MODE ? 5 : 6));
  autoTable(doc, {
    startY: startY + (COMPACT_MODE ? 6 : 8), head: [['Pathway', 'Learning Areas Used', 'Score', 'Performance']], body: pathwayRows.map((row) => [row.pathway, row.learningAreas.join(', ') || 'None', `${formatPathwayNumber(row.score)}/${formatPathwayNumber(row.outOf)}`, `${row.percentage.toFixed(1)}%`]),
    styles: { fontSize: pdfFontSize(doc, COMPACT_MODE ? 6.8 : 8), cellPadding: COMPACT_MODE ? 0.8 : 2 }, headStyles: { fillColor: [226, 239, 247], textColor: [26, 35, 90], fontSize: pdfFontSize(doc, COMPACT_MODE ? 7 : 8) },
    alternateRowStyles: { fillColor: [244, 250, 239] }, tableLineColor: [137, 185, 142], tableLineWidth: 0.25, margin: { left: 14, right: 14 },
  });
  const tableEnd = (doc as any).lastAutoTable.finalY;
  const strongest = strongestPathway(pathwayRows);
  doc.setFont('helvetica', 'bold'); doc.setFontSize(pdfFontSize(doc, 8.5)); doc.setTextColor(26, 35, 126);
  doc.text(`Strongest Pathway: ${strongest?.pathway || '—'} (${strongest?.percentage.toFixed(1) || '0.0'}%)`, 14, tableEnd + 6);
  doc.setFont('helvetica', 'italic'); doc.setFontSize(pdfFontSize(doc, 7.2)); doc.setTextColor(26, 35, 90);
  const narrative = doc.splitTextToSize(`The learner demonstrates a strong inclination towards the ${strongest?.pathway || 'selected'} pathway based on the assessed areas.`, 182);
  doc.text(narrative, 14, tableEnd + 12);
  return tableEnd + 12 + narrative.length * 3.5;
}

// ── Draw Summary Box ─────────────────────────────────────────────────────────
export function drawSummaryBox(
  doc: jsPDF,
  results: any[],
  avgPercentage: number,
  totalPoints: number | null,
  position: string,
  classData: any,
  startY: number,
  streamPosition?: string,
  rankingDetails?: { subjects: string[]; totalMarks: number; totalPoints: number },
): number {
  const hasRankingDetails = Boolean(rankingDetails?.subjects?.length);
  const boxH = hasRankingDetails ? (COMPACT_MODE ? 30 : 40) : (COMPACT_MODE ? 18 : 28);
  startY = ensureReportCardSpace(doc, startY, boxH + 2);
  const isPrimary = getSchoolLevelBand(classData) === 'primary';
  const includedResults = results.filter((result) => !isExcludedResult(result));
  const totalMarks = rankingDetails?.totalMarks ?? includedResults.reduce((s, r) => s + (Number(r.marks || 0)), 0);
  const summaryPoints = rankingDetails?.totalPoints ?? totalPoints;
  const overallGrading = gradeFromPercentage(avgPercentage, classData);
  doc.setFillColor(0, 137, 123); doc.rect(14, startY, 182, boxH, 'F');
  const fs = pdfFontSize(doc, COMPACT_MODE ? 7.2 : 8);
  const gap = COMPACT_MODE ? 5.8 : 8;
  doc.setFontSize(fs); doc.setFont('helvetica', 'bold'); doc.setTextColor(255, 255, 255);
  doc.text(`${is844Curriculum(classData) ? 'Subjects' : 'Learning Areas'}: ${includedResults.length}`, 20, startY + gap);
  doc.text(`Total Marks: ${totalMarks}`, 65, startY + gap);
  doc.text(`Average: ${avgPercentage.toFixed(1)}%`, 130, startY + gap);
  doc.text(`Position: ${position}`, 20, startY + gap * 2);
  doc.text(`Grade: ${overallGrading.grade}`, 65, startY + gap * 2);
  if (!isPrimary && summaryPoints !== null) doc.text(`Total Points: ${summaryPoints}${rankingDetails ? ' / 56' : ''}`, 130, startY + gap * 2);
  if (streamPosition) {
    doc.text(`Stream Position: ${streamPosition}`, 20, startY + gap * 3);
  }
  if (hasRankingDetails && rankingDetails) {
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(pdfFontSize(doc, COMPACT_MODE ? 5.4 : 6.1));
    const rankLabel = is844Curriculum(classData) ? 'KNEC 7-subject rank' : 'Senior 7-subject rank';
    const text = `${rankLabel}: ${rankingDetails.subjects.join(', ')} — ${rankingDetails.totalPoints}/56 points; ${rankingDetails.totalMarks.toFixed(0)}/700 marks`;
    const lines = doc.splitTextToSize(text, 174);
    doc.text(lines, 20, startY + (COMPACT_MODE ? 25 : 33));
  }
  // Leave a clear baseline gap so the deviation line cannot be painted into the summary border.
  return startY + boxH + (COMPACT_MODE ? 3 : 4);
}

// ── Draw Next Term Start Date ──────────────────────────────────────────────────
export function drawNextTermStartDate(
  doc: jsPDF,
  nextTermStartDate: string | null | undefined,
  startY: number
): number {
  if (!nextTermStartDate) return startY;
  
  startY = ensureReportCardSpace(doc, startY, COMPACT_MODE ? 8 : 10);
  const dateObj = new Date(nextTermStartDate);
  const formattedDate = dateObj.toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });
  
  doc.setTextColor(0, 102, 102);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(pdfFontSize(doc, COMPACT_MODE ? 7.5 : 8));
  doc.text(`Next term begins on: ${formattedDate}`, 14, startY);
  doc.setTextColor(0, 0, 0);
  
  return startY + (COMPACT_MODE ? 7 : 8);
}

// ── Draw Deviation ───────────────────────────────────────────────────────────
export function drawDeviation(
  doc: jsPDF,
  deviation: number | null,
  previousAvg: number | null,
  previousPosition: number | null,
  startY: number
): number {
  // No comparison means no deviation line and, importantly, no reserved
  // blank line competing with the required comment/signature zone.
  if (previousAvg === null || previousAvg === undefined) return startY;
  startY = ensureReportCardSpace(doc, startY, COMPACT_MODE ? 10 : 12);
  if (deviation !== null && previousAvg !== null) {
    const arrow = deviation >= 0 ? '\u25B2' : '\u25BC';
    const sign = deviation >= 0 ? '+' : '';
    if (deviation >= 0) doc.setTextColor(76, 175, 80); else doc.setTextColor(244, 67, 54);
    doc.setFont('helvetica', 'bold'); doc.setFontSize(pdfFontSize(doc, COMPACT_MODE ? 7 : 8));
    doc.text(`${arrow} ${sign}${deviation.toFixed(1)}% vs previous (Prev: ${previousAvg?.toFixed(1)}% - Pos: ${previousPosition || 'N/A'})`, 14, startY);
    doc.setTextColor(0, 0, 0);
  } else {
    doc.setTextColor(100, 100, 100); doc.setFont('helvetica', 'normal'); doc.setFontSize(pdfFontSize(doc, COMPACT_MODE ? 7 : 8));
    doc.text(`Previous performance: ${previousAvg.toFixed(1)}% - Position: ${previousPosition || 'N/A'}`, 14, startY);
    doc.setTextColor(0, 0, 0);
  }
  return startY + (COMPACT_MODE ? 7 : 8);
}

export function drawOverallDeviation(
  doc: jsPDF,
  currentTotalMarks: number,
  previousTotalMarks: number | null,
  startY: number,
): number {
  if (previousTotalMarks === null || previousTotalMarks === undefined) {
    // No comparison means no deviation line and no blank vertical reservation.
    return startY;
  }
  startY = ensureReportCardSpace(doc, startY, COMPACT_MODE ? 8 : 10);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(pdfFontSize(doc, COMPACT_MODE ? 6.8 : 8));
  const difference = currentTotalMarks - previousTotalMarks;
  const percent = previousTotalMarks === 0 ? 0 : (difference / previousTotalMarks) * 100;
  doc.setTextColor(difference > 0 ? 22 : difference < 0 ? 190 : 100, difference > 0 ? 128 : difference < 0 ? 45 : 100, difference > 0 ? 65 : difference < 0 ? 45 : 100);
  doc.text(`Overall Deviation: ${difference >= 0 ? '+' : ''}${difference.toFixed(0)} (${percent >= 0 ? '+' : ''}${percent.toFixed(1)}%)`, 14, startY);
  doc.setTextColor(0, 0, 0);
  return startY + (COMPACT_MODE ? 7 : 8);
}

// ── Draw Achievements ────────────────────────────────────────────────────────
export function drawAchievements(
  doc: jsPDF,
  bestSubjects: any[],
  startY: number
): number {
  if (bestSubjects.length === 0) return startY;
  const visibleBestSubjects = COMPACT_MODE ? bestSubjects.slice(0, 3) : bestSubjects;
  const rowH = COMPACT_MODE ? 4.5 : 5;
  const boxHeight = 4 + visibleBestSubjects.length * rowH;
  startY = ensureReportCardSpace(doc, startY, boxHeight + (COMPACT_MODE ? 4 : 6));
  doc.setFillColor(255, 248, 225); doc.rect(14, startY, 182, boxHeight, 'F');
  doc.setFontSize(pdfFontSize(doc, COMPACT_MODE ? 6.5 : 7)); doc.setFont('helvetica', 'bold'); doc.setTextColor(245, 166, 35);
  doc.text('ACHIEVEMENT:', 18, startY + 3.5); doc.setFont('helvetica', 'normal'); doc.setTextColor(0, 0, 0);
  visibleBestSubjects.forEach((b, bi) => {
    const pts = b.points > 0 ? ` (${b.points} pts)` : '';
    doc.text(`Best in ${b.subjectName}: ${b.studentName} (${b.percentage}% — ${b.gradeLabel}${pts})`, 18, startY + 8 + bi * rowH);
  });
  return startY + boxHeight + (COMPACT_MODE ? 1 : 5);
}

// ── Draw AI Comment ──────────────────────────────────────────────────────────

/**
 * Word-wrap text using measured widths, so wrapping is always correct
 * regardless of which font is active when splitting happens.
 */
function wrapCommentText(doc: jsPDF, text: string, fontSize: number): string[] {
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(fontSize);
  const pageWidth = doc.internal.pageSize.getWidth();
  const maxWidth = Math.min(165, Math.max(60, pageWidth - 18 - 14));
  const words = text.split(/\s+/);
  const lines: string[] = [];
  let currentLine = '';
  for (const word of words) {
    if (!word) continue;
    const testLine = currentLine ? `${currentLine} ${word}` : word;
    if (doc.getTextWidth(testLine) <= maxWidth || !currentLine) currentLine = testLine;
    else {
      lines.push(currentLine);
      currentLine = word;
    }
  }
  if (currentLine) lines.push(currentLine);
  return lines.length > 0 ? lines : ['No class teacher comment provided.'];
}

function commentLineHeight(fontSize: number): number {
  return COMPACT_MODE ? fontSize * 0.55 + 0.6 : fontSize * 0.62 + 0.8;
}

function commentHeightAtFont(lineCount: number, fontSize: number): number {
  return 7 + lineCount * commentLineHeight(fontSize) + 3;
}

export interface DrawAICommentOptions {
  /** Bottom edge reserved before drawing signatures/QR/calendar. */
  bottomY?: number;
  /** Minimum fit font for arbitrary long input. */
  minFontSize?: number;
  /** Explicit maximum wrapped lines for the bounded one-page policy. */
  maxLines?: number;
}

/**
 * Conservative preflight for optional trend/achievement blocks. The comment
 * is measured at its normal compact size, so a block is omitted before the
 * required comment needs to be reduced. The actual renderer may fit the
 * comment smaller, but never draws into the reserved signature zone.
 */
export function canFitReportCardOptionalSection(
  doc: jsPDF,
  startY: number,
  optionalHeight: number,
  comment: string,
  schoolInfo?: SchoolInfo,
  qrOptions: ReportCardQrOptions = {},
): boolean {
  const baseFontSize = pdfFontSize(doc, COMPACT_MODE ? 7 : 7.5);
  const lines = wrapCommentText(doc, (comment || 'No class teacher comment provided.').trim(), baseFontSize);
  const commentBottomY = getReportCardCommentBottomY(doc, schoolInfo, qrOptions);
  return startY + optionalHeight + REPORT_CARD_COMMENT_GAP + commentHeightAtFont(lines.length, baseFontSize) <= commentBottomY;
}

export function drawAIComment(
  doc: jsPDF,
  comment: string,
  startY: number,
  options: DrawAICommentOptions = {},
): number {
  const baseFontSize = pdfFontSize(doc, COMPACT_MODE ? 7 : 7.5);
  const minFontSize = Math.min(baseFontSize, options.minFontSize ?? REPORT_CARD_COMMENT_MIN_FONT_SIZE);
  const commentText = (comment || 'No class teacher comment provided.').trim();
  const initialLines = wrapCommentText(doc, commentText, baseFontSize);
  const bottomY = options.bottomY ?? doc.internal.pageSize.getHeight() - REPORT_CONTENT_BOTTOM_MARGIN;
  const availableHeight = Math.max(1, bottomY - startY);
  const headerHeight = 7;
  const contentHeight = Math.max(1, availableHeight - headerHeight - 3);
  const fittedFontSize = Math.max(
    minFontSize,
    Math.min(baseFontSize, (contentHeight / Math.max(1, initialLines.length) - 0.6) / (COMPACT_MODE ? 0.55 : 0.62)),
  );
  const lineHeight = commentLineHeight(fittedFontSize);
  const maxLinesFromHeight = Math.max(1, Math.floor(contentHeight / lineHeight));
  const maxLines = Math.min(options.maxLines ?? REPORT_CARD_COMMENT_MAX_LINES, maxLinesFromHeight);
  // The normal generated comments fit in full. Only genuinely unbounded
  // input reaches this explicit line cap; clipping is preferable to placing
  // text under the QR/signature zone or creating a second page.
  const visibleLines = initialLines.length <= maxLines ? initialLines : initialLines.slice(0, maxLines);
  const boxHeight = Math.min(availableHeight, commentHeightAtFont(visibleLines.length, fittedFontSize));

  doc.setDrawColor(100, 120, 180);
  doc.setLineWidth(0.5);
  doc.setFillColor(232, 234, 246);
  doc.rect(14, startY, 182, boxHeight, 'FD');
  doc.setFontSize(pdfFontSize(doc, 7.5));
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(26, 35, 126);
  doc.text("Class Teacher's Comment:", 18, startY + 4);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(fittedFontSize);
  doc.setTextColor(0, 0, 0);
  visibleLines.forEach((line, index) => doc.text(line, 18, startY + 7 + index * lineHeight));
  return startY + boxHeight + 1;
}
