from pathlib import Path
from PIL import Image, ImageOps

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "public" / "icon-512.png"
RES = ROOT / "android" / "app" / "src" / "main" / "res"
RESOURCES = ROOT / "resources"

source = Image.open(SOURCE).convert("RGBA")
RESOURCES.mkdir(exist_ok=True)
source.save(RESOURCES / "icon.png")

# Keep the icon square and fill the launcher canvas without distortion.
def fit_icon(size: int, transparent: bool = False) -> Image.Image:
    canvas = Image.new("RGBA", (size, size), (0, 0, 0, 0) if transparent else (11, 27, 63, 255))
    icon = ImageOps.contain(source, (size, size), Image.Resampling.LANCZOS)
    if transparent:
        icon = icon.copy()
        # The source icon is already square and opaque; use it as the foreground mark.
        icon.putalpha(255)
    x = (size - icon.width) // 2
    y = (size - icon.height) // 2
    canvas.alpha_composite(icon, (x, y))
    return canvas

# Legacy launcher sizes, matching Android density folders generated by Capacitor.
legacy_sizes = {
    "mipmap-mdpi": 48,
    "mipmap-hdpi": 72,
    "mipmap-xhdpi": 96,
    "mipmap-xxhdpi": 144,
    "mipmap-xxxhdpi": 192,
}
for folder, size in legacy_sizes.items():
    out_dir = RES / folder
    out_dir.mkdir(parents=True, exist_ok=True)
    icon = fit_icon(size)
    icon.save(out_dir / "ic_launcher.png")
    icon.save(out_dir / "ic_launcher_round.png")
    foreground = fit_icon(size, transparent=True)
    foreground.save(out_dir / "ic_launcher_foreground.png")

# Adaptive-icon foreground assets use the same branded mark on a transparent canvas.
for folder, size in legacy_sizes.items():
    foreground = fit_icon(size, transparent=True)
    foreground.save(RES / folder / "ic_launcher_foreground.png")

# Splash assets: a high-contrast navy background with the Zamifu mark centered.
RESOURCES_SPLASH = RESOURCES / "splash.png"
base = Image.new("RGBA", (1080, 1920), (11, 27, 63, 255))
mark = ImageOps.contain(source, (540, 540), Image.Resampling.LANCZOS)
base.alpha_composite(mark, ((base.width - mark.width) // 2, (base.height - mark.height) // 2))
base.convert("RGB").save(RESOURCES_SPLASH, optimize=True)

splash_sizes = {
    "drawable": (480, 320),
    "drawable-port-mdpi": (320, 480),
    "drawable-port-hdpi": (480, 720),
    "drawable-port-xhdpi": (720, 1080),
    "drawable-port-xxhdpi": (1080, 1920),
    "drawable-port-xxxhdpi": (1440, 2560),
    "drawable-land-mdpi": (480, 320),
    "drawable-land-hdpi": (800, 480),
    "drawable-land-xhdpi": (1280, 720),
    "drawable-land-xxhdpi": (1920, 1080),
    "drawable-land-xxxhdpi": (2560, 1440),
}
for folder, size in splash_sizes.items():
    image = Image.new("RGBA", size, (11, 27, 63, 255))
    mark_size = int(min(size) * 0.42)
    mark = ImageOps.contain(source, (mark_size, mark_size), Image.Resampling.LANCZOS)
    image.alpha_composite(mark, ((size[0] - mark.width) // 2, (size[1] - mark.height) // 2))
    out_dir = RES / folder
    out_dir.mkdir(parents=True, exist_ok=True)
    image.convert("RGB").save(out_dir / "splash.png", optimize=True)

print("Generated Zamifu Android launcher icons and splash assets.")
